apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::243699833421:role/eksctl-finops-cluster-nodegroup-ng-NodeInstanceRole-I9b8ZRs0br2u
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::243699833421:role/github-actions-oidc-role
      username: github-actions
      groups:
        - system:masters
