apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::243699833421:role/eksctl-finops-cluster-nodegroup-ng-NodeInstanceRole-I9b8ZRs0br2u
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::243699833421:role/github-actions-oidc-role
      username: github-actions
      groups:
      - system:masters
      
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-13T10:47:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1279"
  uid: f2ab0247-ceb8-4e93-921a-136aad386e88
