apiVersion: apps/v1
kind: Deployment

metadata:
  name: finops-platform
  namespace: finops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: finops-platform

  template:
    metadata:
      labels:
        app: finops-platform

    spec:
      containers:
        - name: finops-platform

          image: ${ECR_IMAGE}:${IMAGE_TAG}

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: finops-config
                  key: AWS_REGION
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: finops-secrets
                  key: newrelic-license-key
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: finops-config
                  key: NEW_RELIC_APP_NAME