apiVersion: apps/v1
kind: Deployment

metadata:
  name: finops-platform
  namespace: finops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: finops-platform

  template:
    metadata:
      labels:
        app: finops-platform

    spec:
      containers:
        - name: finops-platform

          image: 243699833421.dkr.ecr.us-east-1.amazonaws.com/finops-app:ae2c42b9fb58a98b3fc1f25f38d091f1fa46c2b0

          imagePullPolicy: Always

          ports:
            - containerPort: 4000

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"

            limits:
              memory: "256Mi"
              cpu: "500m"

          env:
            - name: AWS_REGION
              value: "us-east-1"

          envFrom:
            - configMapRef:
                name: finops-config