name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: finops-app
  EKS_CLUSTER_NAME: finops-cluster
  AWS_ACCOUNT_ID: 243699833421
  ECR_IMAGE: 243699833421.dkr.ecr.us-east-1.amazonaws.com/finops-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for EKS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::243699833421:role/github-actions-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_IMAGE:$IMAGE_TAG .
          docker push $ECR_IMAGE:$IMAGE_TAG

      - name: Install kubectl and envsubst
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext
      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      - name: Validate cluster access
        run: |
          kubectl config view --raw
          kubectl get namespaces
          kubectl auth can-i get pods

      - name: Ensure namespace exists
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Apply runtime config
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl create secret generic finops-secrets \
            --from-literal=newrelic-license-key="$NEW_RELIC_LICENSE_KEY" \
            -n finops --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Kubernetes application
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_IMAGE: ${{ env.ECR_IMAGE }}
        run: |
          envsubst < k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/service.yaml

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/finops-platform -n finops
          kubectl get pods -n finops
