name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
          -t finops-app:${IMAGE_TAG} .

      - name: Tag Docker Image
        run: |
          docker tag \
          finops-app:${IMAGE_TAG} \
          243699833421.dkr.ecr.us-east-1.amazonaws.com/finops-app:${IMAGE_TAG}

      - name: Push Docker Image
        run: |
          docker push \
          243699833421.dkr.ecr.us-east-1.amazonaws.com/finops-app:${IMAGE_TAG}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region us-east-1 \
          --name finops-cluster

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/finops-platform \
          finops-platform=243699833421.dkr.ecr.us-east-1.amazonaws.com/finops-app:${IMAGE_TAG} \
          -n finops